export const reviews = [
  {
    by: 'Rui Brasil',
    connected: false,
    review: 'This app has been a game-changer for real-time communication.',
    stars: 5,
  },
  {
    by: 'Ricardo Silveira',
    connected: true,
    review: 'This app has streamlined our collaboration process immensely.',
    stars: 2,
  },
  {
    by: 'Pedro Brasil',
    connected: true,
    review: 'This app is fantastic for collaborative design work.',
    stars: 5,
  },
  {
    by: 'Marco Cabral',
    connected: false,
    review: 'This app helps us keep our projects organized and on track.',
    stars: 4,
  },
  {
    by: 'Maria da Silva',
    connected: false,
    review: 'This app is essential for our team communication.',
    stars: 5,
  },
  {
    by: 'Monica Bettencourt',
    connected: true,
    review: 'This app makes our virtual meetings smooth and efficient.',
    stars: 0,
  },
  {
    by: 'Adriana Azevedo',
    connected: false,
    review: 'This app simplifies our payment processing.',
    stars: 5,
  },
  {
    by: 'Luis Miguel',
    connected: true,
    review: 'This app is perfect for managing our emails.',
    stars: 5,
  },
  {
    by: 'Ricardina Pereira',
    connected: false,
    review: 'This app is great for discovering and sharing stories.',
    stars: 4,
  },
  {
    by: 'Luis Azevedo',
    connected: false,
    review: 'This app is reliable for video calls and meetings.',
    stars: 4,
  },
  {
    by: 'Jose Brasil',
    connected: false,
    review: 'This app makes container management so much easier.',
    stars: 2,
  },
  {
    by: 'João Brasil',
    connected: false,
    review: 'This app is crucial for our code version control.',
    stars: 3,
  },
  {
    by: 'Jose Azevedo',
    connected: false,
    review: 'This app is excellent for managing our development projects.',
    stars: 2,
  },
  {
    by: 'Marcelo Cabral',
    connected: false,
    review: 'This app keeps our team connected and engaged.',
    stars: 2,
  },
  {
    by: 'Hugo Paiva',
    connected: false,
    review: 'This app was awesome! Everyone should try it!',
    stars: 1,
  },
]
